### ISSUE TITLE
Why inclusion of Chromium in script?

### ISSUE THREAD

**Issue by sambhav2612** [coderwassananmol/unix-scripts#1]
Doesn't UNIX distributions come with Firefox as default browser and given it the faster, has better memory management,.. than the former so why should we use it even?

**Comment by coderwassananmol** [comment]
Being a Web Developer, I want to make sure of cross-browser compatibility. I always prefer Firefox because it's open source. You may delete the commands.

**Comment by sambhav2612** [comment]
@coderwassananmol makes sense. However, what more can we expect from your end in terms updates/additions to this script to feature other softwares as well?

**Comment by coderwassananmol** [comment]
That totally depends on my availability. Since, I have other commitments to fulfill as well, I shall only be able to contribute in my free time. But yes, you can expect some more advanced shell scripts that set up your system for big softwares where there is a lot of configuration involved especially when something important is usually not mentioned in the docs of some softwares. I will be covering those softwares. I understand that versions change over time and with the help of other contributors we can keep our scripts updated.

**Comment by sambhav2612** [comment]
Great. However, do include some contributing checklist/guidelines for contributors to understand what you're looking from them in terms of updates via PRs.

**Comment by coderwassananmol** [comment]
Sure. I will keep that in mind. Thanks. :)
